from __future__ import annotations

from copy import deepcopy
from typing import Any

_EXAMPLE_IMAGES = [f"data/examples/{index}.jpg" for index in range(1, 9)]


PRESETS: dict[str, dict[str, Any]] = {
    "dino-vits8-attention": {
        "model": {
            "architecture": "vit",
            "backend": "timm",
            "name": "vit_small_patch8_224.dino",
            "pretrained": True,
            "options": {},
        },
        "input": {
            "files": _EXAMPLE_IMAGES,
            "folders": [],
            "patterns": ["*.jpg", "*.jpeg", "*.png", "*.webp"],
            "recursive": False,
            "limit": None,
        },
        "output": {
            "directory": "outputs/dino_vits8_attention",
            "heatmaps": True,
            "overlays": True,
            "grids": True,
            "raw_arrays": False,
            "image_format": "png",
            "raw_format": "npy",
            "overwrite": "replace",
        },
        "analysis": {
            "method": "attention",
            "layers": [2, 5, 8, 11],
            "heads": None,
            "head_fusion": "mean",
        },
        "preprocessing": {
            "image_size": 224,
            "resize": "stretch",
            "crop": "none",
            "pad": "none",
            "interpolation": None,
            "normalize": True,
            "mean": None,
            "std": None,
        },
        "runtime": {
            "batch_size": 8,
            "device": "auto",
            "workers": 0,
            "precision": "float32",
            "seed": None,
        },
        "visualization": {
            "tile_size": None,
            "columns": None,
            "items_per_grid": None,
            "spacing": None,
            "padding": None,
            "labels": None,
            "background": None,
            "dpi": None,
            "overlay_alpha": 0.8,
            "cmap": "viridis",
            "grid_format": "pdf",
            "normalization": "per_map",
            "normalization_range": None,
        },
    },
    "dinov2-reg4-attention": {
        "model": {
            "architecture": "vit",
            "backend": "timm",
            "name": "hf_hub:timm/vit_small_patch14_reg4_dinov2.lvd142m",
            "pretrained": True,
            "options": {},
        },
        "input": {
            "files": _EXAMPLE_IMAGES,
            "folders": [],
            "patterns": ["*.jpg", "*.jpeg", "*.png", "*.webp"],
            "recursive": False,
            "limit": None,
        },
        "output": {
            "directory": "outputs/dinov2_vits14_reg4_attention",
            "heatmaps": True,
            "overlays": True,
            "grids": True,
            "raw_arrays": False,
            "image_format": "png",
            "raw_format": "npy",
            "overwrite": "replace",
        },
        "analysis": {
            "method": "attention",
            "layers": [2, 5, 8, 11],
            "heads": None,
            "head_fusion": "mean",
        },
        "preprocessing": {
            "image_size": 672,
            "resize": "stretch",
            "crop": "none",
            "pad": "none",
            "interpolation": None,
            "normalize": True,
            "mean": None,
            "std": None,
        },
        "runtime": {
            "batch_size": 8,
            "device": "auto",
            "workers": 0,
            "precision": "float32",
            "seed": None,
        },
        "visualization": {
            "tile_size": None,
            "columns": None,
            "items_per_grid": None,
            "spacing": None,
            "padding": None,
            "labels": None,
            "background": None,
            "dpi": None,
            "overlay_alpha": 0.8,
            "cmap": "viridis",
            "grid_format": "pdf",
            "normalization": "per_map",
            "normalization_range": None,
        },
    },
    "dinov2-reg4-rollout": {
        "model": {
            "architecture": "vit",
            "backend": "timm",
            "name": "hf_hub:timm/vit_small_patch14_reg4_dinov2.lvd142m",
            "pretrained": True,
            "options": {},
        },
        "input": {
            "files": _EXAMPLE_IMAGES,
            "folders": [],
            "patterns": ["*.jpg", "*.jpeg", "*.png", "*.webp"],
            "recursive": False,
            "limit": None,
        },
        "output": {
            "directory": "outputs/dinov2_reg4_attention/rollout",
            "heatmaps": True,
            "overlays": True,
            "grids": True,
            "raw_arrays": False,
            "image_format": "png",
            "raw_format": "npy",
            "overwrite": "replace",
        },
        "analysis": {
            "method": "rollout",
            "layers": [2, 5, 8, 11],
            "heads": None,
            "head_fusion": "mean",
        },
        "preprocessing": {
            "image_size": 672,
            "resize": "stretch",
            "crop": "none",
            "pad": "none",
            "interpolation": None,
            "normalize": True,
            "mean": None,
            "std": None,
        },
        "runtime": {
            "batch_size": 8,
            "device": "auto",
            "workers": 0,
            "precision": "float32",
            "seed": None,
        },
        "visualization": {
            "tile_size": None,
            "columns": None,
            "items_per_grid": None,
            "spacing": None,
            "padding": None,
            "labels": None,
            "background": None,
            "dpi": None,
            "overlay_alpha": 0.8,
            "cmap": "viridis",
            "grid_format": "pdf",
            "normalization": "per_map",
            "normalization_range": None,
        },
    },
    "resnet50-gradcam": {
        "model": {
            "architecture": "cnn",
            "backend": "torchvision",
            "name": "resnet50",
            "pretrained": True,
            "options": {},
        },
        "input": {
            "files": _EXAMPLE_IMAGES,
            "folders": [],
            "patterns": ["*.jpg", "*.jpeg", "*.png", "*.webp"],
            "recursive": False,
            "limit": None,
        },
        "output": {
            "directory": "outputs/gradcam",
            "heatmaps": True,
            "overlays": True,
            "grids": True,
            "raw_arrays": False,
            "image_format": "png",
            "raw_format": "npy",
            "overwrite": "replace",
        },
        "preprocessing": {
            "image_size": 672,
            "resize": "stretch",
            "crop": "none",
            "pad": "none",
            "interpolation": None,
            "normalize": True,
            "mean": None,
            "std": None,
        },
        "analysis": {
            "method": "gradcam",
            "target_layer": "layer4",
            "target_class": None,
        },
        "runtime": {
            "batch_size": 8,
            "device": "auto",
            "workers": 0,
            "precision": "float32",
            "seed": None,
        },
        "visualization": {
            "tile_size": None,
            "columns": None,
            "items_per_grid": None,
            "spacing": None,
            "padding": None,
            "labels": None,
            "background": None,
            "dpi": None,
            "overlay_alpha": 0.8,
            "cmap": "viridis",
            "grid_format": "pdf",
            "normalization": "per_map",
            "normalization_range": None,
        },
    },
    "dinov2-pca": {
        "model": {
            "architecture": "vit",
            "backend": "timm",
            "name": "hf_hub:timm/vit_base_patch14_dinov2.lvd142m",
            "pretrained": True,
            "options": {},
        },
        "input": {
            "files": ["data/examples/5.jpg", "data/examples/6.jpg"],
            "folders": [],
            "patterns": ["*.jpg", "*.jpeg", "*.png", "*.webp"],
            "recursive": False,
            "limit": None,
        },
        "output": {
            "directory": "outputs/dinov2_patch_pca",
            "heatmaps": True,
            "overlays": False,
            "grids": True,
            "raw_arrays": False,
            "image_format": "png",
            "raw_format": "npy",
            "overwrite": "replace",
        },
        "preprocessing": {
            "image_size": 672,
            "resize": "stretch",
            "crop": "none",
            "pad": "none",
            "interpolation": None,
            "normalize": True,
            "mean": None,
            "std": None,
        },
        "runtime": {
            "batch_size": 8,
            "device": "auto",
            "workers": 0,
            "precision": "float32",
            "seed": None,
        },
        "analysis": {
            "method": "patch_pca",
            "foreground_threshold": 0.5,
            "foreground_side": "low",
            "projection": "fit",
            "projection_path": None,
            "save_projection": None,
        },
        "visualization": {
            "tile_size": None,
            "columns": None,
            "items_per_grid": None,
            "spacing": None,
            "padding": None,
            "labels": None,
            "background": None,
            "dpi": None,
            "overlay_alpha": 0.45,
            "cmap": "viridis",
            "grid_format": "png",
            "normalization": "per_map",
            "normalization_range": None,
        },
    },
}


def available_presets() -> tuple[str, ...]:
    return tuple(PRESETS)


def get_preset(name: str) -> dict[str, Any]:
    try:
        return deepcopy(PRESETS[name])
    except KeyError as error:
        choices = ", ".join(available_presets())
        raise ValueError(
            f"Unknown preset {name!r}. Available presets: {choices}."
        ) from error
